'use client';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from './layout/navbar';
import Sidebar from './layout/sidebar';
import StoreProvider from '@/lib/StoreProvider';
import { useState } from 'react';

const inter = Inter({ subsets: ['latin'] });

// export const metadata = {
//   title: 'Task Management Dashboard',
//   description: 'Generated by create next app',
// };

export default function RootLayout({ children }) {
  const [page, setPage] = useState('to do');

  return (
    <html lang='en' className='overflow-hidden'>
      <StoreProvider>
        <body className={inter.className}>
          <Navbar>
            <Sidebar>{children}</Sidebar>
          </Navbar>
        </body>
      </StoreProvider>
    </html>
  );
}
