import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from './layout/navbar';
import Sidebar from './layout/sidebar';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Task Management Dashboard',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Navbar>
          <Sidebar>{children}</Sidebar>
        </Navbar>
      </body>
    </html>
  );
}
